# Generated by Django 4.1.4 on 2023-01-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('physical', 'physical'), ('virtual', 'virtual')], default='', max_length=20),
        ),
    ]
