# Generated by Django 4.1.4 on 2022-12-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detalis',
            new_name='details',
        ),
    ]
