# Generated by Django 4.1.4 on 2022-12-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0002_rename_detalis_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allcourse',
            new_name='Allcourses',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='couse',
            new_name='course',
        ),
    ]
