# Generated by Django 4.1.4 on 2022-12-15 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0003_rename_allcourse_allcourses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='il',
        ),
        migrations.RemoveField(
            model_name='details',
            name='sp',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 11, 26, 33, 114215, tzinfo=datetime.timezone.utc), verbose_name='Started from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='ct',
            field=models.CharField(default=datetime.datetime(2022, 12, 15, 11, 27, 8, 235669, tzinfo=datetime.timezone.utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='your_choice',
            field=models.BooleanField(default=False),
        ),
    ]
