# Generated by Django 4.1.4 on 2022-12-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0004_remove_details_il_remove_details_sp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(verbose_name='Started from'),
        ),
    ]
