# Generated by Django 4.1.4 on 2023-01-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, help_text='YYYY-MM-D', null=True)),
                ('date_of_joining', models.DateField(blank=True, help_text='YYYY-MM-D', null=True, verbose_name='died')),
            ],
        ),
    ]
