# Generated by Django 4.1.4 on 2023-01-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('news_desc', models.TextField()),
                ('news_img', models.FileField(default=None, max_length=200, null=True, upload_to='news/')),
            ],
        ),
    ]
