# Generated by Django 4.1.4 on 2023-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.FileField(default=None, max_length=200, null=True, upload_to='media/'),
        ),
    ]
