# Generated by Django 4.1.4 on 2023-01-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_news_news_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_img',
            new_name='file_to',
        ),
    ]
